name: matrix2 ##Working with matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 7, 8]
        include:
          - os: ubuntu-latest
            node_version: 7
            is_ubuntu_7: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8
      #fail-fast: true
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_7: ${{ matrix.is_ubuntu_7 }}
    steps:
      - name: Log node node-version
        run: node -v
      -  uses: actions/setup-node@v2
         with:
          node-version: ${{ matrix.node_version }}
      - name: Log node node-version
        run: |
        node -v